sudo: required

language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"      # might not work 

services:
  - docker

before_install:
  -docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

install:
  - pip install -r myapp/requirements.txt

script:
  - python myapp/tests.py
