sudo: required

language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"      # might not work 

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - pip install -r myapp/requirements.txt

script:
  - python myapp/tests.py
  - docker build -t juanjelgueta/lmmflask .

deploy:
  provider: script
  script: 
    docker push juanjelgueta/lmmflask;
  branch: master




